apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: test-mutate
spec:
  containers:
  - name: nginx
    image: nginx:1.14-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
